### ISSUE TITLE
UX Bugs to Fix Soon(TM)

### ISSUE THREAD

**Issue by A-Nilfgaardian** [EEVengers/ThunderScope#173]
List of all known UX bugs that need to get addressed at some point.

**Known UX Bugs**
- When double clicking a channel in the Vertical widget to remove it as an active channel, it will also select it as the current channel to modify data on. This should not be the case, and if we are disabling a channel it should show a currently active channel as the one we want to change.

**Comment by AleksaBjelogrlic** [comment]
Closing all electron issues due to move to glscopeclient
