### ISSUE TITLE
Matrix community

### ISSUE THREAD

**Issue by ghost** [EEVengers/ThunderScope#236]
Ping @AleksaBjelogrlic 
https://app.element.io
https://matrix.org

**Comment by AleksaBjelogrlic** [comment]
Hi @uranuspucksaxophone! We primarily use discord at the moment, I know it's not perfect, but feel free to join with this link: https://discord.gg/pds7k3WrpK

**Comment by AleksaBjelogrlic** [comment]
The bridge looks like a good solution, reopening the issue

**Comment by AleksaBjelogrlic** [comment]
We are now at #thunderscope:matrix.org on matrix or #thunderscope:libera.chat on IRC. Closed in a timely manner 🙃
