### ISSUE TITLE
issue of impedance control for Thunderscope Rev 4

### ISSUE THREAD

**Issue by gyxxc** [EEVengers/ThunderScope#248]
The second layer below the conditioning circuit is hollowed out, and the third layer is laid with copper as a reference for the insulation layer to control the impedance, which should be controlled by 50 Ω impedance or less. I cannot calculate it out.

**Comment by AleksaBjelogrlic** [comment]
I changed the cutouts to better maintain 50 ohms. They are only under the large pads that would present a discontinuity now
