### ISSUE TITLE
Bug: TS.Net can misinterpret numbers sent over SCPI based on localization settings on Windows

### ISSUE THREAD

**Issue by Johnsel** [EEVengers/ThunderScope#251]
To reproduce set the Language settings in Windows to Dutch. Specifically the number group delimiter will change to '.' (dot) instead of ',' (comma).

This means that ngscopeclient will request divider settings that are off by orders magnitude.

**Comment by AleksaBjelogrlic** [comment]
@Johnsel Moved to https://github.com/macaba/TS.NET/issues/10
