### ISSUE TITLE
macOS support volunteers?

### ISSUE THREAD

**Issue by ochococo** [EEVengers/ThunderScope#252]
Hi, I want to help bringing device support to Darwin platform. 

I cannot do too much on drivers side but can definitely help migrate or build a dedicated application for it. 

If you are someone with experience writing drivers for Darwin, please respond here. 

Mastodon: https://mastodon.social/@oktawian

**Comment by AleksaBjelogrlic** [comment]
Hi @ochococo, we have a prototype mac driver at https://github.com/tech2077/litepcie-macos-driver, it is written and maintained by @tech2077, dev discussions are on our discord (now we have matrix and IRC), feel free to join there! Sorry that this issue slipped by me, I am updating the repo for the beta run and just now saw it.
