### ISSUE TITLE
M2 Thunderbolt CAD sources are missing!

### ISSUE THREAD

**Issue by AnttiLukats** [EEVengers/ThunderScope#262]
M2 Thunderbolt CAD sources are missing!

On crowsourcing you say it is ALL open sourced, but we can not find the Thunderbold CAD part, please update the github!

**Comment by AleksaBjelogrlic** [comment]
Hi @AnttiLukats, this is because it is an off the shelf part - we don't design it and therefore do not have CAD for it. We may design this part in the future and then we will have design files in the repo for it.

**Comment by AnttiLukats** [comment]
OK, Understood, but in that case you should include the PART number of this off the shelf part, so others would know where to get it! Thanks.
